version: '3'

services:
  hub:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    networks:
      - selenium-grid

  e2e:
    build:
      context: ..
      dockerfile: ./e2eTests/Dockerfile
    environment:
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
    depends_on:
      - hub 
      - ayespy_report
    networks:
      - selenium-grid

  ayespy_report:
    image: nginx
    volumes:
      - ./testSite:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
       - "80:80"
    environment:
      - NGINX_PORT=80
    networks:
      - selenium-grid

networks:
  selenium-grid:
